version: '3.7'

services:
  database:
    image: mysql:lts
    container_name: database
    restart: always
    ports:
      - "9020:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}